[package]
name = "lib2600"
version = "0.1.0"
edition = "2024"

[features]
mappers = []
inputs = []
framebuffer = []
debugger = []

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.17"
