[package]
name = "emu_utils"
version = "0.1.0"
edition = "2024"

[dependencies]
delegate = "0.13.5"
num-traits = "0.2.19"
strum_macros = "0.27.2"
thiserror = "2.0.18"

[dev-dependencies]
rstest = "0.26.1"
