[package]
name = "mos6532"
version = "0.1.0"
edition = "2024"

[dependencies]
num-traits = "0.2.19"
paste = "1.0.15"
strum_macros = "0.27.2"
thiserror = "2.0.17"

[dev-dependencies]
rstest = "0.26.1"
