[package]
name = "mos6532"
version = "0.1.0"
edition = "2024"

[dependencies]
emu_utils = { version = "0.1.0", path = "../emu_utils" }
itertools = "0.14.0"
paste = "1.0.15"
thiserror = "2.0.17"

[dev-dependencies]
rstest = "0.26.1"
